version: 2.1

orbs:
  aws-cli: circleci/aws-cli@3.1.1

jobs:
  aws_cli:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Execute Create CFN Stack
          command: |
            CFN_STACK_NAME=RaiseTech-cfn
            aws cloudformation deploy --stack-name "${CFN_STACK_NAME}" --template-file cloudformation/rt_vpc.yml
            aws cloudformation deploy --stack-name "${CFN_STACK_NAME}-sg" --template-file cloudformation/rt_sg.yml
            aws cloudformation deploy --stack-name "${CFN_STACK_NAME}-iam" --template-file cloudformation/rt_iam.yml --capabilities CAPABILITY_NAMED_IAM

workflows:
  infrastructure-ci-workflow:
    jobs:
      - aws_cli
